import c from "../../assets/499Img/sari.jpeg"

import fashion1 from "../../assets/fashion/fashion1.webp";
import fashion2 from "../../assets/fashion/fashion2.webp";
import fashion3 from "../../assets/fashion/fashion3.webp";
import fashion4 from "../../assets/fashion/fashion4.webp";
import fashion5 from "../../assets/fashion/fashion5.webp";
import fashion6 from "../../assets/fashion/fashion6.webp";
import fashion7 from "../../assets/fashion/sari5.webp";
import fashion8 from "../../assets/fashion/sari1.webp";
import fashion9 from "../../assets/fashion/sari2.webp";
import fashion10 from "../../assets/fashion/sari3.webp";
import fashion11 from "../../assets/fashion/sari3.webp";
import fashion12 from "../../assets/fashion/sari4.webp";

import mobile1 from "../../assets/mobile/mobiles1.webp";
import mobile2 from "../../assets/mobile/mobiles2.webp";
import mobile3 from "../../assets/mobile/mobiles3.webp";
import mobile4 from "../../assets/mobile/mobiles4.webp";
import mobile5 from "../../assets/mobile/mobiles5.webp";
import mobile6 from "../../assets/mobile/mobiles6.webp";
import mobile7 from "../../assets/mobile/mobiles7.webp";
import mobile8 from "../../assets/mobile/mobiles8.webp";
import mobile9 from "../../assets/mobile/mobiles9.webp";
import mobile10 from "../../assets/mobile/mobiles10.webp";
import mobile11 from "../../assets/mobile/mobiles11.webp";
import mobile12 from "../../assets/mobile/mobiles12.webp";
import mobile13 from "../../assets/mobile/mobiles13.webp";

import electronics1 from "../../assets/electronics/electronics1.webp";
import electronics2 from "../../assets/electronics/electronics2.webp";
import electronics3 from "../../assets/electronics/electronics3.webp";
import electronics4 from "../../assets/electronics/electronics4.webp";
import electronics5 from "../../assets/electronics/electronics5.webp";
import electronics6 from "../../assets/electronics/electronics6.webp";
import electronics7 from "../../assets/electronics/electronics7.webp";

export const dummyProducts = [
  {
    id: 1,
    name: "Sari",
    description: "Beautiful traditional sari",
    category: "Kilos",
    price: 290.99,
    image: typeof k1 !== 'undefined' ? k1 : c,
    colors: [
      { name: "Red", image: typeof k2 !== 'undefined' ? k2 : c },
      { name: "Blue", image: typeof k3 !== 'undefined' ? k3 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 2,
    name: "oppo",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 390.99,
    image: typeof mobile1 !== 'undefined' ? mobile1 : c,
    colors: [
      { name: "White", image: typeof mobile2 !== 'undefined' ? mobile2 : c },
      { name: "Black", image: typeof mobile3 !== 'undefined' ? mobile3 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.0,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 3,
    name: "Running Shoes",
    description: "Comfortable running shoes",
    category: "Fashion",
    price: 59.99,
    image: typeof fashion1 !== 'undefined' ? fashion1 : c,
    colors: [
      { name: "Gray", image: typeof fashion2 !== 'undefined' ? fashion2 : c },
      { name: "Blue", image: typeof fashion3 !== 'undefined' ? fashion3 : c },
    ],
    sizes: ["8", "9", "10", "11"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: true,
  },
  {
    id: 4,
    name: "Bluetooth Headphones",
    description: "Wireless over-ear headphones",
    category: "Electronics",
    price: 890.99,
    image: typeof electronics1 !== 'undefined' ? electronics1 : c,
    colors: [
      { name: "Black", image: typeof electronics2 !== 'undefined' ? electronics2 : c },
      { name: "White", image: typeof electronics3 !== 'undefined' ? electronics3 : c },
    ],
    sizes: [],
    rating: 4.8,
    offer: "5% off",
    isBestseller: false,
  },
  {
    id: 5,
    name: "Organic Apples",
    description: "Fresh organic apples",
    category: "Home & Furniture",
    price: 3.99,
    image: typeof homeFurniture1 !== 'undefined' ? homeFurniture1 : c,
    colors: [],
    sizes: [],
    rating: 4.7,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 6,
    name: "Yoga Mat",
    description: "Eco-friendly yoga mat",
    category: "Appliances",
    price: 240.99,
    image: typeof appliances1 !== 'undefined' ? appliances1 : c,
    colors: [
      { name: "Green", image: typeof appliances2 !== 'undefined' ? appliances2 : c },
      { name: "Purple", image: typeof appliances3 !== 'undefined' ? appliances3 : c },
    ],
    sizes: ["Standard"],
    rating: 4.3,
    offer: "25% off",
    isBestseller: false,
  },
  {
    id: 7,
    name: "Men's Watch",
    description: "Luxury wrist watch",
    category: "Flight Bookings",
    price: 199.99,
    image: typeof flightBookings1 !== 'undefined' ? flightBookings1 : c,
    colors: [
      { name: "Silver", image: typeof flightBookings2 !== 'undefined' ? flightBookings2 : c },
      { name: "Gold", image: typeof flightBookings3 !== 'undefined' ? flightBookings3 : c },
    ],
    sizes: [],
    rating: 4.6,
    offer: "30% off",
    isBestseller: true,
  },
  {
    id: 8,
    name: "Backpack",
    description: "Durable travel backpack",
    category: "Beauty, Toys & More",
    price: 49.99,
    image: typeof beautyToysMore1 !== 'undefined' ? beautyToysMore1 : c,
    colors: [
      { name: "Navy", image: typeof beautyToysMore2 !== 'undefined' ? beautyToysMore2 : c },
      { name: "Black", image: typeof beautyToysMore3 !== 'undefined' ? beautyToysMore3 : c },
    ],
    sizes: [],
    rating: 4.1,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 9,
    name: "Smartphone",
    description: "Latest model smartphone",
    category: "Two Wheelers",
    price: 999.99,
    image: typeof twoWheelers1 !== 'undefined' ? twoWheelers1 : c,
    colors: [
      { name: "Space Gray", image: typeof twoWheelers2 !== 'undefined' ? twoWheelers2 : c },
      { name: "Silver", image: typeof twoWheelers3 !== 'undefined' ? twoWheelers3 : c },
    ],
    sizes: [],
    rating: 4.9,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 10,
    name: "Kitchen Mixer",
    description: "High-performance kitchen mixer",
    category: "Home & Furniture",
    price: 149.99,
    image: typeof homeFurniture2 !== 'undefined' ? homeFurniture2 : c,
    colors: [
      { name: "Red", image: typeof homeFurniture3 !== 'undefined' ? homeFurniture3 : c },
      { name: "White", image: typeof homeFurniture4 !== 'undefined' ? homeFurniture4 : c },
    ],
    sizes: [],
    rating: 4.4,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 11,
    name: "LED TV",
    description: "4K Ultra HD LED TV",
    category: "Electronics",
    price: 499.99,
    image: typeof electronics4 !== 'undefined' ? electronics4 : c,
    colors: [
      { name: "Black", image: typeof electronics5 !== 'undefined' ? electronics5 : c },
      { name: "Silver", image: typeof electronics6 !== 'undefined' ? electronics6 : c },
    ],
    sizes: [],
    rating: 4.5,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 12,
    name: "Gaming Console",
    description: "Next-gen gaming console",
    category: "Appliances",
    price: 499.99,
    image: typeof appliances4 !== 'undefined' ? appliances4 : c,
    colors: [
      { name: "Black", image: typeof appliances5 !== 'undefined' ? appliances5 : c },
      { name: "White", image: typeof appliances6 !== 'undefined' ? appliances6 : c },
    ],
    sizes: [],
    rating: 4.7,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 13,
    name: "Kids' Toy Set",
    description: "Educational toy set for kids",
    category: "Beauty, Toys & More",
    price: 290.99,
    image: typeof beautyToysMore4 !== 'undefined' ? beautyToysMore4 : c,
    colors: [
      { name: "Multi-color", image: typeof beautyToysMore5 !== 'undefined' ? beautyToysMore5 : c },
    ],
    sizes: [],
    rating: 4.3,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 14,
    name: "Sunglasses",
    description: "Polarized sunglasses",
    category: "Fashion",
    price: 890.99,
    image: typeof fashion4 !== 'undefined' ? fashion4 : c,
    colors: [
      { name: "Black", image: typeof fashion5 !== 'undefined' ? fashion5 : c },
      { name: "Brown", image: typeof fashion6 !== 'undefined' ? fashion6 : c },
    ],
    sizes: [],
    rating: 4.6,
    offer: "25% off",
    isBestseller: false,
  },
  {
    id: 15,
    name: "Blender",
    description: "High-speed blender",
    category: "Home & Furniture",
    price: 99.99,
    image: typeof homeFurniture5 !== 'undefined' ? homeFurniture5 : c,
    colors: [
      { name: "Black", image: typeof homeFurniture6 !== 'undefined' ? homeFurniture6 : c },
      { name: "White", image: typeof homeFurniture7 !== 'undefined' ? homeFurniture7 : c },
    ],
    sizes: [],
    rating: 4.2,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 16,
    name: "Sari 2",
    description: "Beautiful traditional sari",
    category: "Kilos",
    price: 29.99,
    image: typeof fashion7 !== 'undefined' ? fashion7 : c,
    colors: [
      { name: "Red", image: typeof fashion8 !== 'undefined' ? fashion8 : c },
      { name: "Blue", image: typeof fashion9 !== 'undefined' ? fashion9 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 17,
    name: "Shirt 2",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile4 !== 'undefined' ? mobile4 : c,
    colors: [
      { name: "White", image: typeof mobile5 !== 'undefined' ? mobile5 : c },
      { name: "Black", image: typeof mobile6 !== 'undefined' ? mobile6 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.0,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 18,
    name: "Running Shoes 2",
    description: "Comfortable running shoes",
    category: "Fashion",
    price: 59.99,
    image: typeof fashion10 !== 'undefined' ? fashion10 : c,
    colors: [
      { name: "Gray", image: typeof fashion11 !== 'undefined' ? fashion11 : c },
      { name: "Blue", image: typeof fashion12 !== 'undefined' ? fashion12 : c },
    ],
    sizes: ["8", "9", "10", "11"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 19,
    name: "Bluetooth Headphones 2",
    description: "Wireless over-ear headphones",
    category: "Electronics",
    price: 890.99,
    image: typeof electronics7 !== 'undefined' ? electronics7 : c,
    colors: [
      { name: "Black", image: typeof electronics8 !== 'undefined' ? electronics8 : c },
      { name: "White", image: typeof electronics9 !== 'undefined' ? electronics9 : c },
    ],
    sizes: [],
    rating: 4.8,
    offer: "5% off",
    isBestseller: true,
  },
  {
    id: 20,
    name: "Smartwatch",
    description: "Smartwatch with fitness tracking",
    category: "Electronics",
    price: 149.99,
    image: typeof electronics10 !== 'undefined' ? electronics10 : c,
    colors: [
      { name: "Black", image: typeof electronics1 !== 'undefined' ? electronics1 : c },
      { name: "Silver", image: typeof electronics2 !== 'undefined' ? electronics2 : c },
    ],
    sizes: [],
    rating: 4.7,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 21,
    name: "Tablet",
    description: "Portable tablet with high-resolution display",
    category: "Electronics",
    price: 299.99,
    image: typeof electronics3 !== 'undefined' ? electronics3 : c,
    colors: [
      { name: "Black", image: typeof electronics4 !== 'undefined' ? electronics4 : c },
      { name: "White", image: typeof electronics5 !== 'undefined' ? electronics5 : c },
    ],
    sizes: [],
    rating: 4.3,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 22,
    name: "Coffee Maker",
    description: "Automatic coffee machine for home use",
    category: "Appliances",
    price: 790.99,
    image: typeof appliances7 !== 'undefined' ? appliances7 : c,
    colors: [
      { name: "Black", image: typeof appliances8 !== 'undefined' ? appliances8 : c },
      { name: "Red", image: typeof appliances9 !== 'undefined' ? appliances9 : c },
    ],
    sizes: [],
    rating: 4.5,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 23,
    name: "Winter Jacket",
    description: "Warm and stylish winter jacket",
    category: "Fashion",
    price: 129.99,
    image: typeof fashion1 !== 'undefined' ? fashion1 : c,
    colors: [
      { name: "Blue", image: typeof fashion2 !== 'undefined' ? fashion2 : c },
      { name: "Gray", image: typeof fashion3 !== 'undefined' ? fashion3 : c },
    ],
    sizes: ["M", "L", "XL"],
    rating: 4.6,
    offer: "25% off",
    isBestseller: true,
  },
  {
    id: 24,
    name: "Dining Set",
    description: "Elegant dining table with chairs",
    category: "Home & Furniture",
    price: 4995.99,
    image: typeof homeFurniture8 !== 'undefined' ? homeFurniture8 : c,
    colors: [
      { name: "Brown", image: typeof homeFurniture9 !== 'undefined' ? homeFurniture9 : c },
    ],
    sizes: [],
    rating: 4.8,
    offer: "30% off",
    isBestseller: false,
  },
  {
    id: 25,
    name: "Digital Camera",
    description: "Compact digital camera with zoom lens",
    category: "Electronics",
    price: 349.99,
    image: typeof electronics6 !== 'undefined' ? electronics6 : c,
    colors: [
      { name: "Black", image: typeof electronics7 !== 'undefined' ? electronics7 : c },
      { name: "Silver", image: typeof electronics8 !== 'undefined' ? electronics8 : c },
    ],
    sizes: [],
    rating: 4.7,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 26,
    name: "Electric Scooter",
    description: "Eco-friendly electric scooter for urban commute",
    category: "Two Wheelers",
    price: 399.99,
    image: typeof twoWheelers4 !== 'undefined' ? twoWheelers4 : c,
    colors: [
      { name: "White", image: typeof twoWheelers5 !== 'undefined' ? twoWheelers5 : c },
      { name: "Black", image: typeof twoWheelers6 !== 'undefined' ? twoWheelers6 : c },
    ],
    sizes: [],
    rating: 4.2,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 27,
    name: "Perfume",
    description: "Luxury fragrance for women",
    category: "Beauty, Toys & More",
    price: 59.99,
    image: typeof beautyToysMore6 !== 'undefined' ? beautyToysMore6 : c,
    colors: [],
    sizes: [],
    rating: 4.5,
    offer: "20% off",
    isBestseller: true,
  },
  {
    id: 28,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances10 !== 'undefined' ? appliances10 : c,
    colors: [
      { name: "Green", image: typeof appliances1 !== 'undefined' ? appliances1 : c },
    ],
    sizes: [],
    rating: 4.3,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 29,
    name: "Leather Wallet",
    description: "Genuine leather wallet for men",
    category: "Fashion",
    price: 39.99,
    image: typeof fashion4 !== 'undefined' ? fashion4 : c,
    colors: [
      { name: "Brown", image: typeof fashion5 !== 'undefined' ? fashion5 : c },
      { name: "Black", image: typeof fashion6 !== 'undefined' ? fashion6 : c },
    ],
    sizes: [],
    rating: 4.6,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 30,
    name: "Office Chair",
    description: "Comfortable ergonomic office chair",
    category: "Home & Furniture",
    price: 149.99,
    image: typeof homeFurniture10 !== 'undefined' ? homeFurniture10 : c,
    colors: [
      { name: "Black", image: typeof homeFurniture1 !== 'undefined' ? homeFurniture1 : c },
      { name: "Blue", image: typeof homeFurniture2 !== 'undefined' ? homeFurniture2 : c },
    ],
    sizes: [],
    rating: 4.4,
    offer: "20% off",
    isBestseller: false,
  },
  
   
  {
    id: 32,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile10 !== 'undefined' ? mobile10 : c,
    colors: [
      { name: "White", image: typeof mobile11 !== 'undefined' ? mobile11 : c },
      { name: "Black", image: typeof mobile12 !== 'undefined' ? mobile12 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 33,
    name: "iphone 5",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 395.99,
    image: typeof mobile13 !== 'undefined' ? mobile13 : c,
    colors: [
      { name: "White", image: typeof mobile14 !== 'undefined' ? mobile14 : c },
      { name: "Black", image: typeof mobile1 !== 'undefined' ? mobile1 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 34,
    name: "iphone 7",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile2 !== 'undefined' ? mobile2 : c,
    colors: [
      { name: "White", image: typeof mobile3 !== 'undefined' ? mobile3 : c },
      { name: "Black", image: typeof mobile4 !== 'undefined' ? mobile4 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.0,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 35,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile5 !== 'undefined' ? mobile5 : c,
    colors: [
      { name: "White", image: typeof mobile6 !== 'undefined' ? mobile6 : c },
      { name: "Black", image: typeof mobile7 !== 'undefined' ? mobile7 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: true,
  },
  {
    id: 36,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 396.99,
    image: typeof mobile8 !== 'undefined' ? mobile8 : c,
    colors: [
      { name: "White", image: typeof mobile9 !== 'undefined' ? mobile9 : c },
      { name: "Black", image: typeof mobile10 !== 'undefined' ? mobile10 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 37,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile11 !== 'undefined' ? mobile11 : c,
    colors: [
      { name: "White", image: typeof mobile12 !== 'undefined' ? mobile12 : c },
      { name: "Black", image: typeof mobile13 !== 'undefined' ? mobile13 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.0,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 38,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile14 !== 'undefined' ? mobile14 : c,
    colors: [
      { name: "White", image: typeof mobile1 !== 'undefined' ? mobile1 : c },
      { name: "Black", image: typeof mobile2 !== 'undefined' ? mobile2 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 39,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile3 !== 'undefined' ? mobile3 : c,
    colors: [
      { name: "White", image: typeof mobile4 !== 'undefined' ? mobile4 : c },
      { name: "Black", image: typeof mobile5 !== 'undefined' ? mobile5 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 40,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile6 !== 'undefined' ? mobile6 : c,
    colors: [
      { name: "White", image: typeof mobile7 !== 'undefined' ? mobile7 : c },
      { name: "Black", image: typeof mobile8 !== 'undefined' ? mobile8 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.0,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 41,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile9 !== 'undefined' ? mobile9 : c,
    colors: [
      { name: "White", image: typeof mobile10 !== 'undefined' ? mobile10 : c },
      { name: "Black", image: typeof mobile11 !== 'undefined' ? mobile11 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.2,
    offer: "20% off",
    isBestseller: true,
  },
  {
    id: 42,
    name: "Shirt 1",
    description: "Stylish casual shirt",
    category: "Mobiles",
    price: 39.99,
    image: typeof mobile12 !== 'undefined' ? mobile12 : c,
    colors: [
      { name: "White", image: typeof mobile13 !== 'undefined' ? mobile13 : c },
      { name: "Black", image: typeof mobile14 !== 'undefined' ? mobile14 : c },
    ],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 43,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances1 !== 'undefined' ? appliances1 : c,
    colors: [
      { name: "Green", image: typeof appliances2 !== 'undefined' ? appliances2 : c },
    ],
    sizes: [],
    rating: 4.0,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 44,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances3 !== 'undefined' ? appliances3 : c,
    colors: [
      { name: "Green", image: typeof appliances4 !== 'undefined' ? appliances4 : c },
    ],
    sizes: [],
    rating: 4.2,
    offer: "20% off",
    isBestseller: false,
  },
  {
    id: 45,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 1969.99,
    image: typeof appliances5 !== 'undefined' ? appliances5 : c,
    colors: [
      { name: "Green", image: typeof appliances6 !== 'undefined' ? appliances6 : c },
    ],
    sizes: [],
    rating: 4.5,
    offer: "10% off",
    isBestseller: true,
  },
  {
    id: 46,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances7 !== 'undefined' ? appliances7 : c,
    colors: [
      { name: "Green", image: typeof appliances8 !== 'undefined' ? appliances8 : c },
    ],
    sizes: [],
    rating: 4.0,
    offer: "15% off",
    isBestseller: false,
  },
  {
    id: 47,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances9 !== 'undefined' ? appliances9 : c,
    colors: [
      { name: "Green", image: typeof appliances10 !== 'undefined' ? appliances10 : c },
    ],
    sizes: [],
    rating: 4.2,
    offer: "20% off",
    isBestseller: true,
  },
  {
    id: 48,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances1 !== 'undefined' ? appliances1 : c,
    colors: [
      { name: "Green", image: typeof appliances2 !== 'undefined' ? appliances2 : c },
    ],
    sizes: [],
    rating: 4.5,
    offer: "10% off",
    isBestseller: false,
  },
  {
    id: 49,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances3 !== 'undefined' ? appliances3 : c,
    colors: [
      { name: "Green", image: typeof appliances4 !== 'undefined' ? appliances4 : c },
    ],
    sizes: [],
    rating: 4.0,
    offer: "15% off",
    isBestseller: true,
  },
  {
    id: 50,
    name: "Lawn Mower",
    description: "Efficient lawn mower with adjustable height",
    category: "Appliances",
    price: 199.99,
    image: typeof appliances5 !== 'undefined' ? appliances5 : c,
    colors: [
      { name: "Green", image: typeof appliances6 !== 'undefined' ? appliances6 : c },
    ],
    sizes: [],
    rating: 4.2,
    offer: "20% off",
    isBestseller: false,
  }
];

export default dummyProducts;